version: "3"

networks:
  sentio:

services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
      network: host
    container_name: sentio
    working_dir: /var/www/html/sentio
    ports:
      - "80:80"
    environment:
      TZ: UTC+1
      DATABASE: ${DATABASE}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      HOST: ${HOST}
    networks:
      - sentio
    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    build:
      context: ./mysql
      dockerfile: Dockerfile
    container_name: mysql
    restart: unless-stopped
    tty: true
    volumes:
      - ./logs/mysql:/var/log
      - ./logs/mysql/.mysqlsh.log:/root/.mysqlsh/.mysqlsh.log
      - ./data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    networks:
      - sentio
