app = "verba"
primary_region = "sea"

[build]
  image = "adeyomola/verba"

[http_service]
  internal_port = 80
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[vm]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
