app = "verba-mysql"
primary_region = "sea"

[build]
  image = "adeyomola/verba-mysql"

[processes]
  app = "--datadir /data/mysql --default-authentication-plugin caching_sha2_password --performance-schema=OFF --innodb-buffer-pool-size 64M"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
  processes = ["app"]

[mounts]
  source="verbadata"
  destination="/data"
